/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EvaluationChart: typeof import('./src/components/EvaluationChart.vue')['default']
    ParameterDistributionChart: typeof import('./src/components/ParameterDistributionChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SampleTable: typeof import('./src/components/SampleTable.vue')['default']
  }
}
