version: '3.9'

services:
  oracle:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=oracle
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "ls", "/opt/oracle/oradata"]
      interval: 10s
      timeout: 10s
      retries: 30

  backend:
    build:
      context: ./backend
    container_name: soil-backend
    ports:
      - "5000:5000"
    depends_on:
      oracle:
        condition: service_healthy
    environment:
      - STORAGE_MODE=oracle
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: soil-frontend
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev", "--", "--host"]
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  oracle-data:
