version: '3.9'

services:
  oracle:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=oracle
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'SELECT 1 FROM DUAL;' | sqlplus -s system/oracle@localhost:1521/freepdb1 || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - default

  backend:
    build:
      context: ./backend
    container_name: soil-backend
    ports:
      - "5000:5000"
    depends_on:
      oracle:
        condition: service_healthy
    environment:
      - STORAGE_MODE=oracle
    volumes:
      - ./backend:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default

  frontend:
    build:
      context: ./frontend
    container_name: soil-frontend
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev", "--", "--host"]
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default

volumes:
  oracle-data:

networks:
  default:
    driver: bridge
