version: '3.9'

services:
  oracle:
    image: gvenzl/oracle-xe:21.3.0
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: oracle
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
